# Finish configuration for slower but more stable training
env_settings:
    env_path: Build/echo
    num_envs: 2

engine_settings:
    width: 1920
    height: 1080

behaviors:
    Crane:
        trainer_type: ppo
        keep_checkpoints: 1000
        checkpoint_interval: 50000
        max_steps: 1e08
        time_horizon: 128
        summary_freq: 10000
        threaded: true

        hyperparameters:
            batch_size: 1024
            buffer_size: 16384
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 12
            learning_rate_schedule: linear

        network_settings:
            normalize: false
            hidden_units: 512
            num_layers: 2
            vis_encode_type: simple

        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
            curiosity:
                strength: 0.02
                gamma: 0.99
                encoding_size: 256

# Add this section
environment_parameters:
    level_parameter:
        curriculum:
            - name: Swing control
              completion_criteria:
                  measure: reward
                  behavior: Crane
                  signal_smoothing: true
                  min_lesson_length: 1000
                  threshold: 2.8
              value: 0

            - name: End
              completion_criteria:
                  measure: reward
                  behavior: Crane
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 1
                  require_reset: true
              value: -1
