# Finish configuration for slower but more stable training
env_settings:
    env_path: Build/crane
    num_envs: 8

engine_settings:
    width: 640
    height: 480

behaviors:
    Crane:
        trainer_type: ppo
        keep_checkpoints: 1000
        checkpoint_interval: 100000
        max_steps: 1e08
        time_horizon: 128
        summary_freq: 1000
        threaded: true

        hyperparameters:
            batch_size: 1024
            buffer_size: 16384
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 12
            learning_rate_schedule: linear

        network_settings:
            normalize: false
            hidden_units: 512
            num_layers: 2
            vis_encode_type: simple

        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
            curiosity:
                strength: 0.01
                gamma: 0.99
                encoding_size: 256


# Add this section
environment_parameters:
    level_parameter:
        curriculum:
            - name: MoveToPoint
              completion_criteria:
                  measure: reward
                  behavior: Crane
                  signal_smoothing: false
                  min_lesson_length: 1000
                  threshold: 4800
              value: 0          
