behaviors:
    Crane:
        trainer_type: ppo
        keep_checkpoints: 1000
        checkpoint_interval: 500000
        max_steps: 1e08
        time_horizon: 128
        summary_freq: 1000       
        threaded: true

        hyperparameters:
            batch_size: 1024
            buffer_size: 10240
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 12
            learning_rate_schedule: linear

        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
            vis_encode_type: simple

        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
            curiosity:
                strength: 0.01
                gamma: 0.99
                encoding_size: 256

environment_parameters:
  spreaderHeight:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Crane
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 2.5
        value: 22
          
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Crane
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 2.5
        value: 17

      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Crane
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 2.5          
        value: 15
          
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Crane
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 2.5          
        value: 10

      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Crane
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 2.5          
        value: 3

      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: Crane
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 2.8       
        value: 3
