env_settings:
    env_path: Build/crane
    num_envs: 1

engine_settings:
    width: 640
    height: 480

behaviors:
  Crane:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 20000
  
environment_parameters:
  level_parameter:
    curriculum:
      - name: Move above container
        completion_criteria:
          measure: reward
          behavior: Crane
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 0
        
      - name: Lesson3
        value: 1
  