behaviors:
  Crane:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 50000
      buffer_init_steps: 10000
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.75
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 1.0
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: demos/CD-Single-no-swi.demo
    keep_checkpoints: 5
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 10000
