env_settings:
  env_path: Build/Echo
  env_args: null
  base_port: 5005
  num_envs: 24
  seed: -1

engine_settings:
  width: 256
  height: 256
  quality_level: 5
  time_scale: 20
  no_graphics: true

behaviors:
  Crane:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024 #512
      buffer_size: 51200 #25600
      learning_rate: 0.0002
      beta: 0.01
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      use_recurrent: false
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        strength: 0.1
        gamma: 0.99
      gail:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: demos/CDS-RP.demo

        
    keep_checkpoints: 5000
    max_steps: 1e08
    time_horizon: 64
    summary_freq: 20000
    #behavioral_cloning:
      #demo_path: demos/CD-Single-no-swi.demo
      #steps: 2000000
      #strength: 1.0
      #samples_per_update: 0